[package]
name = "homeworker-api-client"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
serde = { version = "1.0.139", features = ["derive"] }
serde_json = "1.0.83"
chrono = { version = "0.4.22", features = ["serde"] }
url = { version = "2.2.2", features = ["serde"] }

ehttp = "0.2.0"
