[package]
name = "homeworker"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
time = { version = "0.3", features = ["serde-human-readable"] }
url = { version = "2.3", features = ["serde"] }

reqwest = { version = "0.11", features = ["json"] }
